name: Deploy EC2 Instance

on:
  workflow_run:
    workflows: ["Deploy VPC"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: select terraform action
        options:
        - apply
        - destroy
        required: true

jobs:
  deploy_ec2:
    name: Terraform Deploy EC2 Instance
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform-EC2

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Terraform init 
      run: terraform init 
    
    - name: Check if VPC exists
      id: check_vpc
      run: |
        if terraform state show aws_vpc.my_vpc >/dev/null 2>&1; then
          echo "::set-output name=vpc_exists::true"
        else
          echo "::set-output name=vpc_exists::false"
        fi
      
    - name: Terraform Validate
      run: terraform validate
          
    - name: Terraform Plan 
      run: terraform plan 
        
    - name: Terraform Apply
      if: ${{ github.event.inputs.terraform_action == 'apply' && steps.check_vpc.outputs.vpc_exists != 'true' }}
      run: terraform apply --auto-approve 

    - name: Terraform Destroy
      if: ${{ github.event.inputs.terraform_action == 'destroy' && steps.check_vpc.outputs.vpc_exists == 'true' }}
      run: terraform destroy --auto-approve  
