name: Deploy EC2 Instance

on:
  workflow_run:
    workflows: ["Create VPC"]
    types:
      - completed

jobs:
  create-ec2:
    name: Terraform Deploy Nginx AWS EC2
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform-EC2

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Terraform init 
      run: terraform init 
      
    - name: Terraform Validate
      run: terraform validate
          
    - name: Terraform Plan 
      run: terraform plan 
        
    - name: Terraform apply 
      run: terraform apply --auto-approve 
